### PR TITLE
Change juju terraform provider verison (in plugins) to 0.10.1

### PR DESCRIPTION
**Pull request by chanchiwai-ray**
Change juju terraform provider version to `0.10.1` in all the terraform plans in the plugins. Use `base` instead of deprecated `series` for charm resource. Also ran `terraform fmt` to write the terraform plans to a canonical format.

### CODE REVIEW

**Comment by hemanthnakkina** [comment]
/canonical/self-hosted-runners/run-workflows 7848bf165c0efa9c9980363803795b6afd6dba87

**Review by rgildein — APPROVED** [review]
LGTM

**Review by agileshaw — APPROVED** [review]
Changes LGTM. But I was wondering whether we would want to loosen the version pin to `~> 0.10.1` to get auto-updates on micro versions.

**Review by hemanthnakkina — APPROVED** [review]
LGTM, thanks for the PR!

**Comment by hemanthnakkina** [comment]
> Changes LGTM. But I was wondering whether we would want to loosen the version pin to `~> 0.10.1` to get auto-updates on micro versions.

Since the juju terraform provider does not have its first 1.x release and given the experience with previous juju terraform provider releases I prefer to pin to a specific version for now.

**Pull request merged**
