### PR TITLE
Refresh MAAS doc links

### PR DESCRIPTION
**Pull request by nobuto-m**
[404]
https://maas.io/docs/using-network-tags

[redirected to unexpected page]
https://maas.io/docs/ip-ranges

Closes-Bug: https://bugs.launchpad.net/snap-openstack/+bug/2066379
Closes-Bug: https://bugs.launchpad.net/snap-openstack/+bug/2066386

### CODE REVIEW

**Comment by wolsen** [comment]
/canonical/self-hosted-runners/run-workflows 335be3a

**Review by gboutry — APPROVED** [review]
Thank you for this, we'll need to revisit later if we keep these docs links if they move too often.

**Comment by nobuto-m** [comment]
> edit: All commits need to be signed

Ah, I forgot about it again. Can the check be enabled as the first job of the CI so we get the feedback immediately?

**Comment by nobuto-m** [comment]
Signing the commit changes the commit id, and I've pushed the new one now.

**Comment by gboutry** [comment]
> > edit: All commits need to be signed
> 
> Ah, I forgot about it again. Can the check be enabled as the first job of the CI so we get the feedback immediately?

I've opened this PR: https://github.com/canonical/snap-openstack/pull/238

**Comment by gboutry** [comment]
/canonical/self-hosted-runners/run-workflows e25fa7d

**Comment by nobuto-m** [comment]
The func test failure was:
>  Timed out while waiting for model 'openstack' to be ready
> Error: Timed out while waiting for model 'openstack' to be ready
> Error: Process completed with exit code 1.

**Pull request merged**
