### PR TITLE
Refactor package structure

### PR DESCRIPTION
**Pull request by gboutry**
Changes:
 - `jobs` -> `core`: this package outgrown its initial purpose and is
   the package where we put important classes to manage the deployment
 - `commands` -> `steps`: Lots of the modules in the `commands` package
   held no commands but where a registry of steps to use to deploy
   the different parts.

The long term goal is to create import rules, for example:
 - core is forbidden to import from steps and commands

### CODE REVIEW

**Comment by hemanthnakkina** [comment]
Can we rename sunbeam/versions.py to constants.py and move into core? We can move some constants like OPENSTACK_MODEL etc to this file? What do you think?

**Comment by hemanthnakkina** [comment]
Can we move JujuStepHelper from sunbeam/steps/juju.py to sunbeam/core/juju.py since the class is used by classes other than sunbeam/steps/juju.py

**Comment by gboutry** [comment]
1: I don't see it as a contradiction, JujuStepHelper is either used in the steps package, provider package or in the feature modules, which can draw from the steps package.
2: That's what I intended, but didn't want to get this in this PR, a lot of things already moved around, I can do it
3: I always felt this was the natural direction, (already happened in the maas provider). They can still live in their respective module at the moment.

**Comment by hemanthnakkina** [comment]
> 1: I don't see it as a contradiction, JujuStepHelper is either used in the steps package, provider package or in the feature modules, which can draw from the steps package. 2: That's what I intended, but didn't want to get this in this PR, a lot of things already moved around, I can do it 3: I always felt this was the natural direction, (already happened in the maas provider). They can still live in their respective module at the moment.

For (1) JujuStepHelper predominantly gives functionality that is missing from JujuHelper (rather python-libjuju). And so to me it makes sense if JujuStepHelper is part of `core`.

Makes sense for your points (2), (3) - can be separate PRs later on.

**Review by hemanthnakkina — APPROVED** [review]

**Pull request merged**
